### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [hayashi-toshihiro/share_clip#73]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
挙動確認できました。LGTMです。

## 静的コードチェックが入っている
・概ね良いかと思います。ただClipPostsControllerのindexアクションのifの分岐などはメソッドとして切り出したり、モデルに処理を寄せるなどしましょう。
・UsersControllerのget_user_stamp内にあるtemplate変数に代入している文字列は定数化しても良いかと思います。
・services/twithc_api.rbですが、重複している箇所は共通化、Clinent-ID, Authorizationなど、もし外部に見えてしまうと良くないものだったら、credentialsを使って秘匿化したりしましょう（外部に見えてしまうと不味い場合は、新しい値を習得、古いものを削除した上で秘匿化しましょう）。

## 就活において十分な技術力を示せる機能を実装しているか
・結論から申しますと、十分な技術力を示せる水準には達していない印象を受けました。
・レコメンド機能（おすすめの表示）・マルチ検索・オートコンプリート（類似タグ作成しないためにも欲しい）を優先して実装しましょう。
・上記に合わせて以下の機能も実装に加えられないか検討してみてください。
```
◯通知
概要：FacebookやTwitterでもおなじみの通知機能があります。その人に関連するお知らせをリアルタイムで通知することで、ユーザーの行動を促し、アクティブ率を向上させます。

使用技術・ライブラリ：
- WebSocket通信・ActionCable（Rails標準）

◯チャット
概要：FacebookメッセンジャーやSNSなどには、チャット機能が必ずついています。現在では、WebSocketを用いることで、リアルタイムでやり取りが可能となっています。コツさえ掴めば、比較的簡単に実装できます。ダイレクトメッセージのようなチャット機能を実装することで、ユーザー同士のコミュニケーションを活性化させることができるかもしれません。
使用技術・ライブラリ：
- WebSocket
  - https://ja.wikipedia.org/wiki/WebSocket
- ActionCable（Rails標準）
  - https://railsguides.jp/action_cable_overview.html
```

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・レスポンシブ対応しましょう。
・使う色を絞りましょう。参考：https://book.impress.co.jp/books/1119101155
・左・中央・右のページ構成になっていますが、それぞれ役割をハッキリさせたほうが良いかと思います。右はゲームの列挙、中央はコンテンツといったようにしたいかと思うと、新規登録とログインが右上にあるのに違和感を感じました。
・利用規約・プライバシーポリシー・お問い合わせの配置を調整しましょう。中央に配置するのか、必ず表示画面の下部に表示する必要があるのか、表示されたリンクが押しやすいかetcを考えて調整しましょう。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by hayashi-toshihiro** [comment]
> ・概ね良いかと思います。ただClipPostsControllerのindexアクションのifの分岐などはメソッドとして切り出したり、モデルに処理を寄せるなどしましょう。
・UsersControllerのget_user_stamp内にあるtemplate変数に代入している文字列は定数化しても良いかと思います。
・services/twithc_api.rbですが、重複している箇所は共通化、Clinent-ID, Authorizationなど、もし外部に見えてしまうと良くないものだったら、credentialsを使って秘匿化したりしましょう（外部に見えてしまうと不味い場合は、新しい値を習得、古いものを削除した上で秘匿化しましょう）。

**Comment by Tsuchiya2** [comment]
ご対応ありがとうございます。
引き続き開発頑張ってください。

**Comment by Tsuchiya2** [comment]
> レコメンド機能（おすすめの表示）・マルチ検索・オートコンプリート（類似タグ作成しないためにも欲しい）を優先して実装しましょう。

こちらを1つでも実装できたら本リリース、引き続き開発を進めながら就活の流れで良いかと思います。

**Comment by hayashi-toshihiro** [comment]
了解しました！！
ありがとうございます！！
